export const SET_GLOBALERROR = 'SET_GLOBALERROR';
export const CLEAR_GLOBALERROR = 'CLEAR_GLOBALERROR';
export const SET_GLOBALERRORS = 'SET_GLOBALERRORS';
export const CLEAR_GLOBALERRORS = 'CLEAR_GLOBALERRORS';
export const SET_TITLE = 'SET_TITLE';
export const SET_INDEX = 'SET_INDEX';
